name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  qr_code_scanner: ^1.0.1
  speech_to_text: ^6.6.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  shared_preferences: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/vectors/vector_12_x2.svg
  - assets/vectors/vector_10_x2.svg
  - assets/vectors/vector_15_x2.svg
  - assets/vectors/verify_svgrepo_com_6_x2.svg
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/vector_3_x2.svg
  - assets/vectors/vector_19_x2.svg
  - assets/vectors/vector_13_x2.svg
  - assets/vectors/vector_11_x2.svg
  - assets/vectors/vector_25_x2.svg
  - assets/vectors/vector_22_x2.svg
  - assets/vectors/verify_svgrepo_com_1_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/vectors/vector_23_x2.svg
  - assets/vectors/vector_17_x2.svg
  - assets/vectors/vector_21_x2.svg
  - assets/vectors/user_x2.svg
  - assets/images/whats_app_image_20240810_at_91043_am_1.jpeg
  - assets/vectors/layer_15_x2.svg
  - assets/vectors/vector_4_x2.svg
  - assets/vectors/vector_20_x2.svg
  - assets/vectors/vector_26_x2.svg
  - assets/vectors/verify_svgrepo_com_3_x2.svg
  - assets/vectors/vector_14_x2.svg
  - assets/vectors/layer_14_x2.svg
  - assets/vectors/group_x2.svg
  - assets/vectors/layer_1_x2.svg
  - assets/vectors/layer_11_x2.svg
  - assets/vectors/layer_16_x2.svg
  - assets/vectors/layer_17_x2.svg
  - assets/vectors/layer_12_x2.svg
  - assets/vectors/layer_13_x2.svg
  - assets/images/cat_profile_1.png
  - assets/vectors/lock_x2.svg
  - assets/vectors/user_1_x2.svg
  - assets/vectors/vector_16_x2.svg
  - assets/vectors/verify_svgrepo_com_2_x2.svg
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/vector_8_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/vector_5_x2.svg
  - assets/vectors/vector_9_x2.svg
  - assets/vectors/vector_24_x2.svg
  - assets/vectors/vector_18_x2.svg
  - assets/vectors/verify_svgrepo_com_5_x2.svg
  - assets/vectors/verify_svgrepo_com_x2.svg
  - assets/vectors/verify_svgrepo_com_4_x2.svg

